openapi: 3.0.3
info:
  title: Simple Wallet API
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Local development server

paths:
  /wallet:
    post:
      summary: Create a new wallet
      responses:
        '201':
          description: Wallet created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
        '500':
          description: Internal server error

    get:
      summary: Get wallet balance
      parameters:
        - name: wallet_id
          in: query
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  balance:
                    type: integer
                    example: 1500
        '400':
          description: Missing or invalid wallet_id
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "invalid_wallet_id"
        '404':
          description: Wallet not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "wallet_not_found"

  /wallet/deposit:
    post:
      summary: Deposit money into wallet
      parameters:
        - name: wallet_id
          in: query
          required: true
          schema:
            type: integer
            example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: integer
                  minimum: 1
                  example: 1000
              required: [amount]
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  transaction_id:
                    type: integer
                    example: 1
                  new_balance:
                    type: integer
                    example: 2500
        '400':
          description: Invalid amount or wallet_id
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "amount_must_be_positive"
        '404':
          description: Wallet not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "wallet_not_found"

  /wallet/withdraw:
    post:
      summary: Withdraw money from wallet
      parameters:
        - name: wallet_id
          in: query
          required: true
          schema:
            type: integer
            example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: integer
                  minimum: 1
                  example: 500
              required: [amount]
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  transaction_id:
                    type: integer
                    example: 2
                  new_balance:
                    type: integer
                    example: 2000
        '400':
          description: Invalid amount
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "amount_must_be_positive"
        '404':
          description: Wallet not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "wallet_not_found"
        '422':
          description: Insufficient funds
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "insufficient_funds"

  /wallet/transactions:
    get:
      summary: Get transaction history for a wallet
      parameters:
        - name: wallet_id
          in: query
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    amount:
                      type: integer
                      example: 1000
                    type:
                      type: string
                      enum: [deposit, withdrawal]
                      example: "deposit"
        '400':
          description: Missing or invalid wallet_id
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "invalid_wallet_id"
        '404':
          description: Wallet not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "wallet_not_found"